# Generated by Django 4.2.6 on 2023-11-17 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiempo', '0002_remove_tiempo_description_remove_tiempo_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tiempo',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='tiempo',
            name='latitude',
            field=models.FloatField(default=''),
        ),
        migrations.AddField(
            model_name='tiempo',
            name='longitude',
            field=models.FloatField(default=''),
        ),
        migrations.AddField(
            model_name='tiempo',
            name='temperature',
            field=models.FloatField(default=''),
        ),
        migrations.AddField(
            model_name='tiempo',
            name='wind_speed',
            field=models.FloatField(default=''),
        ),
    ]
