# Generated by Django 4.2.6 on 2023-11-17 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiempo', '0003_tiempo_description_tiempo_latitude_tiempo_longitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tiempo',
            name='description',
            field=models.TextField(default=0),
        ),
        migrations.AlterField(
            model_name='tiempo',
            name='latitude',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='tiempo',
            name='longitude',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='tiempo',
            name='temperature',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='tiempo',
            name='wind_speed',
            field=models.FloatField(default=0),
        ),
    ]
