# Generated by Django 4.2.6 on 2023-11-17 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiempo', '0004_alter_tiempo_description_alter_tiempo_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tiempo',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='tiempo',
            name='wind_speed',
            field=models.FloatField(),
        ),
    ]
