# Generated by Django 4.2.6 on 2023-11-17 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tiempo', '0005_alter_tiempo_description_alter_tiempo_wind_speed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tiempo',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='tiempo',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='tiempo',
            name='temperature',
        ),
        migrations.RemoveField(
            model_name='tiempo',
            name='wind_speed',
        ),
    ]
