# Generated by Django 4.2.6 on 2023-10-13 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('codigo', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=90)),
                ('descripcion', models.CharField(max_length=2000)),
                ('fecha', models.DateTimeField()),
                ('imagen', models.FileField(upload_to='static/assets/')),
                ('publish', models.BooleanField(default=True)),
            ],
        ),
    ]
