# Generated by Django 4.2.5 on 2023-10-13 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portafolio', '0002_alter_proyecto_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='imagen',
            field=models.FileField(null=True, upload_to='proyectos/'),
        ),
    ]
